services:
  - type: web
    name: kimobe
    runtime: static
    repo: https://github.com/bshamloufard/Kimobe
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
